Services
dhagandev/LiUniv_Onboarding pull request #9
Opened 2018-07-12 15:44 UTC by dhagandev

Twitter related logic moved to its own service

2018-07-12 18:23 UTC, kev-chan requested changes

2018-07-12 18:23 UTC, kev-chan commented on src/main/java/liuni/resources/LiUniResource.java
> +        twitterService = TwitterService.getInstance();
you are hardcoding the index in the resource class, if you're doing that i'd recommend cleaning up the code

2018-07-12 18:23 UTC, kev-chan commented on src/main/java/liuni/resources/LiUniResource.java
>      public LiUniResource() {
this is never used, clean it up

2018-07-12 18:23 UTC, kev-chan commented on src/main/java/liuni/resources/LiUniResource.java
> +import liuni.services.TwitterService;
call the <name>Driver class -> <name>Application

2018-07-12 18:23 UTC, kev-chan commented on src/main/java/liuni/services/TwitterService.java
> +    public static final int TWITTER_CHAR_MAX = 280;
keep all of the static variables together

2018-07-12 18:23 UTC, kev-chan commented on src/main/java/liuni/services/TwitterService.java
> +    private static Logger logger = LoggerFactory.getLogger(TwitterService.class);
this can be final as well

2018-07-12 18:23 UTC, kev-chan commented on src/main/java/liuni/services/TwitterService.java
> +        int statusLength = convertedArr.length;
why is this being converted to a char[]?

2018-07-12 20:28 UTC, kev-chan requested changes

2018-07-12 20:28 UTC, kev-chan commented on src/main/java/liuni/LiUniApplication.java
> +        final LiUniResource resource = new LiUniResource(config, index);
why are you passing in the index?

2018-07-12 20:28 UTC, kev-chan commented on src/main/java/liuni/services/TwitterService.java
> +    private final static TwitterService INSTANCE = new TwitterService();
lazy load this

2018-07-12 20:31 UTC, dhagandev commented on src/main/java/liuni/LiUniApplication.java
> +        final LiUniResource resource = new LiUniResource(config, index);
Allows you to switch between users in the yml file, is there a better way to be indicating which user you should use?

2018-07-12 20:41 UTC, kev-chan commented on src/main/java/liuni/LiUniApplication.java
> +        final LiUniResource resource = new LiUniResource(config, index);
there is, give it some thought

2018-07-12 20:41 UTC, kev-chan commented on src/main/java/liuni/services/TwitterService.java
> +    private static volatile TwitterService INSTANCE = null;
you don't need volatile/synchronized

2018-07-13 19:00 UTC, kev-chan requested changes
update the error message when auth credentials to be more professional.  no Chromedino

2018-07-13 19:00 UTC, kev-chan commented on application-example.yml
> +    - userName:
come up with a better variable name for what this value actual represents, variable name is confusing

2018-07-13 19:00 UTC, kev-chan commented on application-example.yml
> +  defaultuser: 0
same for this one, better variable name

2018-07-13 21:19 UTC, kev-chan requested changes

2018-07-13 21:19 UTC, kev-chan commented on application-example.yml
> +  users:
call this account instead of user

2018-07-13 21:55 UTC, merged